### ISSUE TITLE
Non-relative brand link

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaComputing/MultiDocumenter.jl#29]
We want the brand link to go back to SciML.ai in https://docs.sciml.ai/Overview/stable/, but it's setup to be relative so that fails.

**Comment by pfitzseb** [comment]
I don't think this is a good idea. Redirecting to a different page when clicking on the brand image seems very unexpected to me.

**Comment by ChrisRackauckas** [comment]
Then what else would we do with it? It shouldn't be "Home" because it's not labelled and that already has a button?

**Comment by pfitzseb** [comment]
Mh, fair. I'd rather remove the "Home" entry then, I think.

**Comment by ChrisRackauckas** [comment]
But then it won't build the landing page docs 😅

**Comment by pfitzseb** [comment]
Yeah I know. That I can fix though :)
