### ISSUE TITLE
Search bar does not work due to hardcoded search link

### ISSUE THREAD

**Issue by Datseris** [JuliaComputing/MultiDocumenter.jl#65]
I've succesfully built a multidocumenter build, https://juliadynamics.github.io/DynamicalSystemsDocs.jl/attractors/stable/ .

The search bar does not work at all. 

User @mortenpi suggested that 

"""
Morten Piibeleht
  [< 1 minute ago](https://julialang.slack.com/archives/C66L48G1X/p1693903574723969?thread_ts=1693903459.333619&cid=C66L48G1X)
It tries to load it from https://juliadynamics.github.io/search-data/content.cfg.json, rather than https://juliadynamics.github.io/DynamicalSystemsDocs.jl/search-data/content.cfg.json

Morten Piibeleht
  [< 1 minute ago](https://julialang.slack.com/archives/C66L48G1X/p1693903595369099?thread_ts=1693903459.333619&cid=C66L48G1X)
That said, if you deploy it to https://juliadynamics.github.io/, then it should work

Morten Piibeleht
  [< 1 minute ago](https://julialang.slack.com/archives/C66L48G1X/p1693903608288979?thread_ts=1693903459.333619&cid=C66L48G1X)
But we should fix the absolute-ish URL regardless
"""

**Comment by pfitzseb** [comment]
Doesn't https://github.com/JuliaComputing/MultiDocumenter.jl/pull/48 address this?
