### ISSUE TITLE
Raw HTML displayed on demo site https://juliacomputing.github.io/MultiDocumenter.jl/

### ISSUE THREAD

**Issue by fingolfin** [JuliaComputing/MultiDocumenter.jl#80]
Going to https://juliacomputing.github.io/MultiDocumenter.jl/ I get redirected to https://juliacomputing.github.io/MultiDocumenter.jl/inf/stable/ which shows some raw HTML, which I think is meant to insert the Infiltrator.jl logo. 

![Image](https://github.com/user-attachments/assets/cced93ae-f5a2-4c77-b598-fee253a1d240)

In contrast this is how it look at <https://juliadebug.github.io/Infiltrator.jl/stable/>

![Image](https://github.com/user-attachments/assets/42829c0e-c988-4c42-b68b-5c9a089296fe)

**Comment by pfitzseb** [comment]
This was an issue in Infiltrator's docs, which got fixed in 1.7 or 1.8. The page at https://juliacomputing.github.io/MultiDocumenter.jl/stable/ didn't get
